### ISSUE TITLE
Provide an implementation of the ScriptArchive which doesn't require disk IO

### ISSUE THREAD

**Issue by jameskojo** [Netflix/Nicobar#12]
Per discussion with @abersnaze , which should avoid hard dependencies on local disk, since that has caused issues before in API.next.
To accomplish this, we should try and find a way to avoid using URLs to represent resources. Failing that, provide a custom UrlStreamHandler which can point to a location in memory.

**Comment by vasanth-asokan** [comment]
We are not pursuing this as of the moment, as disks have proved reliable enough in practical operation.
