### ISSUE TITLE
URLConnection cache prevents updating JARs with the JarArchiveRepository

### ISSUE THREAD

**Issue by bquenin** [Netflix/Nicobar#37]
Sun's default implementation of JarURLConnection caches JARs.

Therefore, when using a JarArchiveRepository with a poller and replacing an existing jar with an updated JAR having the same name, and therefore the same URL, results in the cached JAR to be used instead of the new one.

The only workaround I found is to disable JarURLConnection caching and it then works as expected:

``` java
private void disableURLConnectionCache() {
        URL url = null;
        try {
            url = new URL("jar:file://dummy.jar!/");
        } catch (MalformedURLException e) {
            // Ignore
        }
        URLConnection urlConnection = new URLConnection(url) {
            @Override
            public void connect() throws IOException {
                // NOOP
            }

        };
        urlConnection.setDefaultUseCaches(false);
    }
```

Did I miss something?

Regards,
BQ.

**Comment by whisperwing** [comment]
@bertrand-quenin I'm having the same issue with the nicobar-example. Could you elaborate on how to use this function you provided to disable cache please? Thanks
