### ISSUE TITLE
ScriptModuleloader: add re-link support

### ISSUE THREAD

**Issue by jameskojo** [Netflix/Nicobar#5]
* Add the ability to declare a dependency on a range of versions
* Provide a mechanism to safely re-link the existing modules with any new versions that were deployed.

Billy mentioned the desire of using a red/black style deployment of new modules. That's should be a separate work item, but whatever we come up with here should take that use-case into account.

**Comment by vasanth-asokan** [comment]
Closing as not fix, pending further feedback / input.
