### ISSUE TITLE
How to define and import my own targetClass in ScriptModuleUtils.findAssignableClass?

### ISSUE THREAD

**Issue by weikuo0506** [Netflix/Nicobar#50]
In the GroovyModuleLoaderExample.java :
Class<?> callable = ScriptModuleUtils.findAssignableClass(scriptModule, Callable.class);
If we define our own targetClass ,for example: 
Class<?> transfer = ScriptModuleUtils.findAssignableClass(scriptModule, ITransfer.class);
error happends:
Caused by: java.lang.NoClassDefFoundError: com/demo/ITransfer

I notice that in JBossModuleUtils.java, NICOBAR_CORE_DEPENDENCY_SPEC has been created by adding pathFilter. Of course ,if we add "com/demo" in pathFilter, it work. But, obvious, it shouldn't do so.

Is there any other way to make it work? that is, make JBossModuleClassLoader import my own interface?

**Comment by weikuo0506** [comment]
got it:
public ScriptModuleLoader.Builder addAppPackages(@Nullable java.util.Set<String> incomingPaths)
Specify a set of packages to make available from the application classloader as runtime dependencies for all scripts loaded by this script module.

**Comment by vasanth-asokan** [comment]
Thanks, glad you were able to find the interface for adding your own application packages!
