### ISSUE TITLE
ScriptRepo/ScriptModuleLoader: Add pluggable eviction policy

### ISSUE THREAD

**Issue by jameskojo** [Netflix/Nicobar#6]
Provide a plugable mechanism to clean up the repo of un-needed or under-utilized scripts in order to re-claim permgen.
* usage based eviction
* space based eviction
* add a mechanism to safely unload a script module

we should make sure to release the classloader and references to all resources to ensure that the perm-gen space is reclaimed.

**Comment by vasanth-asokan** [comment]
These concerns seem out of scope for nicobar core. Closing as never fix.
