### ISSUE TITLE
ScriptModuleLoader: provide a mechanism to bind dependency on application classloader resources

### ISSUE THREAD

**Issue by jameskojo** [Netflix/Nicobar#7]
From a practical perspective, script module will have to utilize resources from the shared application classloader and the system classloader.
E.G.
* JRE/JDK classes
* scriptlib-core
* logging/insights
* cobertura (for unit tests)
* etc

Provide a generic way of defining groups of resources and classes that should be shared, and provide a mechanism to declare a dependency on those resourses.
jboss-modules already provides the ability to declare a "filtered" dependency on a classlaoder such that only a pre-declared set of resources will "leak" through the classloader depedency. I think the work here is mainly figuring out how to specify exactly which groups of classes should leak through and providing a generic mechanism for specifying and discovering those groups at script authoring time.

**Comment by vasanth-asokan** [comment]
Script module utils provides classpath scanning utilities. Script module loader can be built with a specific package whitelist to leak through from app. So I think we are good here for now.
